"""empty message

Revision ID: c7ff6ac527cd
Revises: 
Create Date: 2017-12-11 13:27:07.802180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7ff6ac527cd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('careers', 'slug')
    op.drop_column('careers', 'image_filename')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('careers', sa.Column('image_filename', sa.VARCHAR(), nullable=True))
    op.add_column('careers', sa.Column('slug', sa.VARCHAR(length=200), nullable=True))
    # ### end Alembic commands ###
